### ISSUE TITLE
关于模块化和组件化

### ISSUE THREAD

**Issue by madongqiang2201** [LiushuiXiaoxia/AndroidModular#2]
嗨，有个问题想请教一下，关于模块化和组件化，你认为这两种叫法有区别吗？看了不少文章，有强行解释的，有说没区别的，看着也比较乱，您在模块化开发实践过程中，是怎么理解这两个概念的呢？谢谢

**Comment by LiushuiXiaoxia** [comment]
个人理解就是划分的颗粒度，比如公司内部多个业务有多个app，需要有统一的具有公司logo形式的下拉刷新，这个是业务无关的，可以理解为组件。再比如统一的日志框架，埋点等。

如果一个app业务复杂，且多人协作，那么可以按照业务的维度来划分， 比如订单，购物车等，这种跟业务强关联的，那么可以认为是一个模块，一个模块他可能会包含多个基本组件，比如上面说到的日志，埋点等。

以上就是我对组件化和模块化的理解，希望有所帮助。
